name: Workflow - Build EMOD; create artifacts

on:
  # Allows re-use in other workflows
  workflow_call:
    inputs:
      disease_type:
        required: true
        type: string
      science_test:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      scons_option: ${{ inputs.disease_type != 'All' && format('--Disease={0}', inputs.disease_type) || ' ' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set buildenv image ref
        id: image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "ref=ghcr.io/${OWNER}/dtk-ubuntu-buildenv:latest" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check python; build executable; strip symbols; make schema; extract version
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/EMOD" \
            ${{ steps.image.outputs.ref }} \
            bash -c "\
              python3 --version && \
              python3 -m pip list && \
              cd /EMOD && \
              scons --Release --jobs=4 ${{ env.scons_option }} ${{ inputs.science_test }} && \
              strip build/x64/Release/Eradication/Eradication && \
              ./build/x64/Release/Eradication/Eradication --get-schema --schema-path schema.json && \
              grep DTK_Version schema.json | sed 's/[^0-9.]//g' > version\
            "
      - name: Archive binary
        uses: actions/upload-artifact@v6
        with:
          name: Eradication
          path: ./build/x64/Release/Eradication/Eradication
          retention-days: 7
      - name: Archive schema
        uses: actions/upload-artifact@v6
        with:
          name: schema.json
          path: schema.json
          retention-days: 7
      - name: Archive version
        uses: actions/upload-artifact@v6
        with:
          name: version
          path: version
          retention-days: 7
      - name: Archive component tests
        if: ${{ inputs.disease_type == 'All' }}
        uses: actions/upload-artifact@v4
        with:
          name: componentTests
          path: ./build/x64/Release/componentTests/componentTests
          retention-days: 7
